services:
  radio:
    build: .
    image: wcp-widget-radio
    container_name: wcp-widget-radio
    ports:
      - "3741:3741"
    environment:
      - CONTAINER_NAME=wcp-widget-radio
    restart: unless-stopped
    volumes:
      - ./published:/app/published
